### ISSUE TITLE
Add support for runtime configuration

### ISSUE THREAD

**Issue by arbrandes** [openedx/frontend-app-discussions#387]
frontend-platform supports runtime configuration since 2.5.0 (see [the PR](https://github.com/openedx/frontend-platform/pull/335) that introduced it), but it requires MFE cooperation.  We should avoid making configuration values constant, in order to make it possible to change them after initialization.

### Failure on stage

The change was first merged to master in 9f84230c, but it was reported to introduce an issue as described in https://github.com/openedx/frontend-app-discussions/pull/382.  The change was reverted by 67b0b33a.

We need to either try and reproduce the issue to gather more data, or try to find out what's wrong by analyzing the code.
    
### PRs

- [x] https://github.com/openedx/frontend-app-discussions/pull/379 (merged)
- [x] https://github.com/openedx/frontend-app-discussions/pull/382 (revert)
- [x] https://github.com/openedx/frontend-app-discussions/pull/386 (second attempt)

**Comment by arbrandes** [comment]
@asadazam93, I took the liberty of assigning us both to this issue. I'm going to need your help in either trying to reproduce the problem or in analyzing what might be going on.

Thanks in advance!

**Comment by asadazam93** [comment]
@arbrandes have you updated anything in this PR? OR do you want to just merge and try to debug on stage?

**Comment by arbrandes** [comment]
@asadazam93, there are no changes yet: I want to take another visual pass at it to see if there are any glaring (or hidden) problems.  It would be great to debug it on stage early next week: maybe we can schedule a call to do it synchronously, and thus hopefully faster.

Thanks!

**Comment by asadazam93** [comment]
@arbrandes we merged and deployed again on stage. Strangely there was no issue this time around and it seems to be working fine. I am not sure why but it seems it was just a deployment glitch that caused the failure last time around.

**Comment by mehaknasir** [comment]
We have deployed the code to production and the production environment is working fine too. we are good to close this issue.

**Comment by arbrandes** [comment]
Wow, this is awesome!  I was pretty worried about this one... Gladly, it was unfounded.  Thanks a lot @asadazam93 and @mehaknasir!
