### ISSUE TITLE
Post Type UI Doesn't change inside learning 

### ISSUE THREAD

**Issue by CodeWithEmad** [openedx/frontend-app-discussions#673]
When trying to create a post, inside learning MFE, the Discussion/Question border highlight doesn't change on click.

![Screenshot from 2024-02-27 15-55-52](https://github.com/openedx/frontend-app-discussions/assets/49523567/56c82c3b-5752-4719-bc3e-5fdae1828302)

Tested on Quince.2 
Tutor 17.0.2

**Comment by awais-ansari** [comment]
I have merged a fix on the Quince branch. @CodeWithEmad Can you please confirm whether this issue still exists or not? Thanks!

**Comment by awais-ansari** [comment]
https://github.com/openedx/frontend-app-discussions/pull/677

**Comment by CodeWithEmad** [comment]
Thanks @awais-ansari! That should do it.
